# Podstawowe operacje w numpy

Warto przeczytać tytułem wstępu Tutorial Numpy: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

Głównym obiektem NumPy jest wielowymiarowa tablica. 
Jest to tabela elementów (zazwyczaj liczb), wszystkich tego samego typu, indeksowanych przez krotkę dodatnich liczb całkowitych. Wymiarach w NumPy nazywane są osiami (axes). Liczba osi to jest ranga (rank).

Na przykład współrzędne punktu w przestrzeni 3D [1, 2, 1] to tablica rzędu 1, ponieważ ma jedną oś. Oś ta ma długość 3. W przykładzie przedstawionym poniżej tablica ma rangę 2 (jest dwuwymiarowa). Pierwszy wymiar (oś) ma długość 2, drugi wymiar ma długość 3.

In [1]:
z = [[ 1., 0., 0.],
 [ 0., 1., 2.]]

Klasa tablic w NumPy to ndarray. 

Warto zauważyć, że numpy.array oferuje więcej niż tablica klasy Class.array w standardowym Python, która obsługuje tylko tablice jednowymiarowe i oferuje mniej funkcji. Ważniejsze atrybuty obiektu ndarray to:

ndarray.ndim
    Liczba osi (wymiary) tablicy. W pythonie liczba wymiarów jest określana jako ranga.

ndarray.shape
    Wymiary tablicy. Jest to krotka liczb całkowitych wskazujących rozmiar tablicy w każdym wymiarze. 
    Dla macierzy z n rzędami i kolumnami m, shape będzie (n, m).
    
ndarray.dtype
    Obiekt opisujący typ elementów tablicy. Numpy.int32, numpy.int16 i numpy.float64 to przykłady.

### Tworzenie tablic numpy (ndarray)

Tablice ndarray możemy tworzyć na kilka sposobów.

Tablicę ndarray można utworzyć ze zwykłej listy lub krotki pythonowej za pomocą funkcji array:

In [2]:
import numpy as np
a = np.array(z)
a.shape

(2, 3)

Array przekształca sekwencje sekwencji w tablice dwuwymiarowe, sekwencje sekwencji sekwencji w trójwymiarowe tablice i tak dalej.

In [4]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Typ tablicy można również wyraźnie określić w czasie tworzenia:

In [5]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Funkcja zeros tworzy tablicę pełną zer.

Funkcja ones tworzą tablicę pełną jedynek.

Funkcja empty tworzy tablicę, której początkowa zawartość jest losowa i zależy od stanu pamięci. Domyślnie dtype utworzonej tablicy jest float64.

In [6]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones( (2,3,4) )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Możemy też tworzyć losowo wygnerowane tablice ndarray dowolnych wymiarów:

In [8]:
b = np.random.random( (2,3) )
b

array([[0.73684958, 0.27211333, 0.45313508],
       [0.15307994, 0.8835705 , 0.51709487]])

Aby utworzyć sekwencje liczb, NumPy udostępnia funkcję analogiczną do range ze zwykłego pythona: arange

In [9]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

### Wybrane operacje na tablicach ndarray

Funkcja reshape pozwala na zmianę wymiarowości (shape) tablicy:

In [10]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Na tablicach ndarray możemy wykonywać operacje arytmetyczne. Mnożenie macierzy metodą dot product oraz elemwise:

In [11]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )

print(A*B)
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


### Adresowanie i wycinanie fragmentów tablic

Można wycinać (slicing) fragmenty tablic ndarray:

In [12]:
A = np.array([
[11,12,13,14,15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51,52,53,54,55]])

print(A[3:5])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [13]:
print(A[:,3])

[14 24 34 44 54]


In [39]:
x = [1, 2, 3]
y = [4, 5, 6]
z = np.array( [x,y] )
print(z)
print(z.T)




[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [41]:

x = np.tile([0, 1, 2], 4)
print(x)
y = x.reshape( (2,6) )
print(y)

[0 1 2 0 1 2 0 1 2 0 1 2]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [47]:
print(y.flatten())

[0 1 2 0 1 2 0 1 2 0 1 2]


In [62]:
b = np.random.randint(100, size=(100,100) )
print(b)
np.average(b)

[[19 15  2 ...  9 37 97]
 [63 39 43 ... 54 43 61]
 [38 84 46 ... 30 84 55]
 ...
 [53 47 37 ... 84 95 96]
 [16  5 44 ... 99 26 36]
 [59 52 59 ...  2  3 56]]


49.189